### ISSUE TITLE
strsplit error in view(df_summary)

### ISSUE THREAD

**Issue by VictorSuarezL** [dcomtois/summarytools#64]
Since the last month, every time I try to make a dfSummary wrap with view function throw the same error:

``` r
summarytools::view(summarytools::dfSummary(mtcars))
#> Error in strsplit(s, ""): argumento de tipo no-carácter
```
Is there any way I can fix it? Thanks in adv!
<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by dcomtois** [comment]
By loading the package first, it works...
```r
library(summarytools)
view(dfSummary(mtcars))
``` 
I'll look into it though, thx for reporting.

**Comment by dcomtois** [comment]
Fixed,

**Comment by heinonmatti** [comment]
I'm getting this same error, with and without first loading summarytools (Package version is 0.9.2.)

`summarytools::view(summarytools::dfSummary(df_codebook), file = "./codebook_concise.html")`
#> Error in strsplit(s, "") : non-character argument

Sorry for not being able to give a reproducible example!

Here's my session info: 

- Session info ---------------------------------------------------------------------------------------------------------------------------------

- Packages -------------------------------------------------------------------------------------------------------------------------------------
 package               * version    date       lib source                              
 abind                   1.4-5      2016-07-21 [1] CRAN (R 3.5.0)                      
 acepack                 1.4.1      2016-10-29 [1] CRAN (R 3.5.0)                      
 assertthat              0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                      
 backports               1.1.3      2018-12-14 [1] CRAN (R 3.5.1)                      
 base64enc               0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                      
 BayesFactor             0.9.12-4.2 2018-05-19 [1] CRAN (R 3.5.0)                      
 bayesplot               1.6.0      2018-08-02 [1] CRAN (R 3.5.1)                      
 BDgraph                 2.56       2019-03-19 [1] CRAN (R 3.5.3)                      
 BiasedUrn               1.07       2015-12-28 [1] CRAN (R 3.5.0)                      
 bitops                  1.0-6      2013-08-17 [1] CRAN (R 3.5.0)                      
 boot                    1.3-20     2017-08-06 [2] CRAN (R 3.5.3)                      
 brew                    1.0-6      2011-04-13 [1] CRAN (R 3.5.0)                      
 bridgesampling          0.6-0      2018-10-21 [1] CRAN (R 3.5.1)                      
 brms                  * 2.8.0      2019-03-15 [1] CRAN (R 3.5.3)                      
 brmstools             * 0.5.3      2018-11-16 [1] Github (mvuorre/brmstools@dc9c1dd)  
 Brobdingnag             1.2-6      2018-08-13 [1] CRAN (R 3.5.1)                      
 broom                   0.5.1      2018-12-05 [1] CRAN (R 3.5.1)                      
 broom.mixed             0.2.4      2019-02-21 [1] CRAN (R 3.5.1)                      
 broomExtra              0.0.1      2019-03-13 [1] CRAN (R 3.5.3)                      
 callr                   3.2.0      2019-03-15 [1] CRAN (R 3.5.3)                      
 car                     3.0-2      2018-08-23 [1] CRAN (R 3.5.1)                      
 carData                 3.0-2      2018-09-30 [1] CRAN (R 3.5.1)                      
 cellranger              1.1.0      2016-07-27 [1] CRAN (R 3.5.0)                      
 checkmate               1.9.1      2019-01-15 [1] CRAN (R 3.5.2)                      
 cli                     1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                      
 cluster                 2.0.7-1    2018-04-13 [1] CRAN (R 3.5.0)                      
 coda                    0.19-2     2018-10-08 [1] CRAN (R 3.5.1)                      
 codetools               0.2-16     2018-12-24 [2] CRAN (R 3.5.3)                      
 coin                    1.3-0      2019-03-08 [1] CRAN (R 3.5.3)                      
 colorspace              1.4-1      2019-03-18 [1] CRAN (R 3.5.3)                      
 colourpicker            1.0        2017-09-27 [1] CRAN (R 3.5.0)                      
 corpcor                 1.6.9      2017-04-01 [1] CRAN (R 3.5.0)                      
 cowplot                 0.9.4      2019-01-08 [1] CRAN (R 3.5.2)                      
 crayon                  1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                      
 crosstalk               1.0.0      2016-12-21 [1] CRAN (R 3.5.0)                      
 curl                    3.3        2019-01-10 [1] CRAN (R 3.5.2)                      
 d3Network               0.5.2.1    2015-01-31 [1] CRAN (R 3.5.0)                      
 data.table              1.12.0     2019-01-13 [1] CRAN (R 3.5.2)                      
 data.tree               0.7.8      2018-09-24 [1] CRAN (R 3.5.1)                      
 DEoptimR                1.0-8      2016-11-19 [1] CRAN (R 3.5.0)                      
 desc                    1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                      
 DescTools               0.99.28    2019-03-17 [1] CRAN (R 3.5.3)                      
 devtools                2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                      
 DiagrammeR              1.0.0      2018-03-01 [1] CRAN (R 3.5.0)                      
 digest                  0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                      
 diptest                 0.75-7     2016-12-05 [1] CRAN (R 3.5.0)                      
 downloader              0.4        2015-07-09 [1] CRAN (R 3.5.0)                      
 dplyr                 * 0.8.0.1    2019-02-15 [1] CRAN (R 3.5.2)                      
 DT                      0.5        2018-11-05 [1] CRAN (R 3.5.1)                      
 dygraphs                1.1.1.6    2018-07-11 [1] CRAN (R 3.5.1)                      
 ellipsis                0.1.0      2019-02-19 [1] CRAN (R 3.5.1)                      
 emmeans                 1.3.3      2019-03-02 [1] CRAN (R 3.5.3)                      
 EMT                     1.1        2013-01-29 [1] CRAN (R 3.5.2)                      
 estimability            1.3        2018-02-11 [1] CRAN (R 3.5.0)                      
 evaluate                0.13       2019-02-12 [1] CRAN (R 3.5.1)                      
 expm                    0.999-4    2019-03-21 [1] CRAN (R 3.5.3)                      
 ez                      4.4-0      2016-11-02 [1] CRAN (R 3.5.3)                      
 fdrtool                 1.2.15     2015-07-08 [1] CRAN (R 3.5.0)                      
 fit.models              0.5-14     2017-04-06 [1] CRAN (R 3.5.1)                      
 forcats               * 0.4.0      2019-02-17 [1] CRAN (R 3.5.2)                      
 foreach                 1.4.4      2017-12-12 [1] CRAN (R 3.5.0)                      
 foreign                 0.8-71     2018-07-20 [1] CRAN (R 3.5.1)                      
 Formula                 1.2-3      2018-05-03 [1] CRAN (R 3.5.0)                      
 fs                      1.2.7      2019-03-19 [1] CRAN (R 3.5.3)                      
 generics                0.0.2      2018-11-29 [1] CRAN (R 3.5.1)                      
 GGally                  1.4.0      2018-05-17 [1] CRAN (R 3.5.0)                      
 ggcorrplot              0.1.2      2018-09-11 [1] CRAN (R 3.5.1)                      
 ggExtra                 0.8        2018-04-04 [1] CRAN (R 3.5.0)                      
 ggm                     2.3        2015-01-21 [1] CRAN (R 3.5.0)                      
 ggplot2               * 3.1.0      2018-10-25 [1] CRAN (R 3.5.1)                      
 ggrepel                 0.8.0      2018-05-09 [1] CRAN (R 3.5.0)                      
 ggridges              * 0.5.1      2018-09-27 [1] CRAN (R 3.5.1)                      
 ggsignif                0.5.0      2019-02-20 [1] CRAN (R 3.5.2)                      
 ggstatsplot           * 0.0.10     2019-03-17 [1] CRAN (R 3.5.3)                      
 glasso                  1.10       2018-07-13 [1] CRAN (R 3.5.1)                      
 glmnet                  2.0-16     2018-04-02 [1] CRAN (R 3.5.0)                      
 glue                    1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                      
 GPArotation             2014.11-1  2014-11-25 [1] CRAN (R 3.5.2)                      
 gridExtra               2.3        2017-09-09 [1] CRAN (R 3.5.0)                      
 groupedstats            0.0.6      2019-03-20 [1] CRAN (R 3.5.3)                      
 gtable                  0.3.0      2019-03-25 [1] CRAN (R 3.5.1)                      
 gtools                  3.8.1      2018-06-26 [1] CRAN (R 3.5.0)                      
 haven                   2.1.0      2019-02-19 [1] CRAN (R 3.5.2)                      
 Hmisc                   4.2-0      2019-01-26 [1] CRAN (R 3.5.2)                      
 hms                     0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                      
 htmlTable               1.13.1     2019-01-07 [1] CRAN (R 3.5.2)                      
 htmltools               0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                      
 htmlwidgets             1.3        2018-09-30 [1] CRAN (R 3.5.1)                      
 httpuv                  1.5.0      2019-03-15 [1] CRAN (R 3.5.3)                      
 httr                    1.4.0      2018-12-11 [1] CRAN (R 3.5.1)                      
 huge                    1.3.1      2019-03-11 [1] CRAN (R 3.5.3)                      
 igraph                  1.2.4      2019-02-13 [1] CRAN (R 3.5.2)                      
 influenceR              0.1.0      2015-09-03 [1] CRAN (R 3.5.0)                      
 inline                  0.3.15     2018-05-18 [1] CRAN (R 3.5.0)                      
 insight                 0.1.2      2019-03-05 [1] CRAN (R 3.5.3)                      
 IsingFit                0.3.1      2016-09-07 [1] CRAN (R 3.5.1)                      
 IsingSampler            0.2        2015-03-02 [1] CRAN (R 3.5.0)                      
 iterators               1.0.10     2018-07-13 [1] CRAN (R 3.5.1)                      
 jmv                     0.9.6      2018-12-11 [1] CRAN (R 3.5.1)                      
 jmvcore                 0.9.5.2    2018-12-10 [1] CRAN (R 3.5.1)                      
 jpeg                    0.1-8      2014-01-23 [1] CRAN (R 3.5.0)                      
 jsonlite                1.6        2018-12-07 [1] CRAN (R 3.5.1)                      
 knitr                 * 1.22       2019-03-08 [1] CRAN (R 3.5.3)                      
 labelled                2.1.0      2019-02-25 [1] CRAN (R 3.5.3)                      
 later                   0.8.0      2019-02-11 [1] CRAN (R 3.5.1)                      
 lattice                 0.20-38    2018-11-04 [2] CRAN (R 3.5.3)                      
 latticeExtra            0.6-28     2016-02-09 [1] CRAN (R 3.5.0)                      
 lavaan                  0.6-3      2018-09-22 [1] CRAN (R 3.5.2)                      
 lazyeval                0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                      
 libcoin                 1.0-4      2019-02-28 [1] CRAN (R 3.5.3)                      
 lme4                    1.1-21     2019-03-05 [1] CRAN (R 3.5.3)                      
 lmtest                  0.9-36     2018-04-04 [1] CRAN (R 3.5.0)                      
 loo                     2.1.0      2019-03-13 [1] CRAN (R 3.5.3)                      
 lubridate               1.7.4      2018-04-11 [1] CRAN (R 3.5.0)                      
 magick                  2.0        2018-10-05 [1] CRAN (R 3.5.2)                      
 magrittr                1.5        2014-11-22 [1] CRAN (R 3.5.0)                      
 manipulate              1.0.1      2014-12-24 [1] CRAN (R 3.5.0)                      
 markdown                0.9        2018-12-07 [1] CRAN (R 3.5.1)                      
 MASS                    7.3-51.1   2018-11-01 [1] CRAN (R 3.5.2)                      
 Matrix                  1.2-17     2019-03-22 [1] CRAN (R 3.5.3)                      
 matrixcalc              1.0-3      2012-09-15 [1] CRAN (R 3.5.0)                      
 MatrixModels            0.4-1      2015-08-22 [1] CRAN (R 3.5.0)                      
 matrixStats             0.54.0     2018-07-23 [1] CRAN (R 3.5.1)                      
 MBESS                   4.4.3      2018-01-10 [1] CRAN (R 3.5.0)                      
 mc2d                    0.1-18     2017-03-06 [1] CRAN (R 3.5.0)                      
 memoise                 1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                      
 metafor                 2.0-0      2017-06-22 [1] CRAN (R 3.5.2)                      
 mgcv                    1.8-28     2019-03-21 [1] CRAN (R 3.5.3)                      
 mime                    0.6        2018-10-05 [1] CRAN (R 3.5.1)                      
 miniUI                  0.1.1.1    2018-05-18 [1] CRAN (R 3.5.0)                      
 minpack.lm              1.2-1      2016-11-20 [1] CRAN (R 3.5.0)                      
 minqa                   1.2.4      2014-10-09 [1] CRAN (R 3.5.0)                      
 mnormt                  1.5-5      2016-10-15 [1] CRAN (R 3.5.0)                      
 modelr                  0.1.4      2019-02-18 [1] CRAN (R 3.5.1)                      
 modeltools              0.2-22     2018-07-16 [1] CRAN (R 3.5.1)                      
 multcomp                1.4-10     2019-03-05 [1] CRAN (R 3.5.3)                      
 multcompView            0.1-7      2015-07-31 [1] CRAN (R 3.5.0)                      
 munsell                 0.5.0      2018-06-12 [1] CRAN (R 3.5.0)                      
 mvtnorm                 1.0-10     2019-03-05 [1] CRAN (R 3.5.2)                      
 NetworkComparisonTest * 2.0.1      2016-10-29 [1] CRAN (R 3.5.0)                      
 nlme                    3.1-137    2018-04-07 [1] CRAN (R 3.5.0)                      
 nloptr                  1.2.1      2018-10-03 [1] CRAN (R 3.5.1)                      
 nnet                    7.3-12     2016-02-02 [2] CRAN (R 3.5.3)                      
 nortest                 1.0-4      2015-07-30 [1] CRAN (R 3.5.0)                      
 openxlsx                4.1.0      2018-05-26 [1] CRAN (R 3.5.0)                      
 pacman                * 0.5.1      2019-03-11 [1] CRAN (R 3.5.3)                      
 paletteer               0.2.1      2019-02-13 [1] CRAN (R 3.5.2)                      
 pander                  0.6.3      2018-11-06 [1] CRAN (R 3.5.1)                      
 papaja                * 0.1.0.9842 2018-11-18 [1] Github (crsh/papaja@2e11aec)        
 patchwork             * 0.0.1      2018-11-21 [1] Github (thomasp85/patchwork@fd7958b)
 pbapply                 1.4-0      2019-02-05 [1] CRAN (R 3.5.2)                      
 pbivnorm                0.6.0      2015-01-23 [1] CRAN (R 3.5.0)                      
 pcaPP                   1.9-73     2018-01-14 [1] CRAN (R 3.5.0)                      
 pillar                  1.3.1      2018-12-15 [1] CRAN (R 3.5.1)                      
 pkgbuild                1.0.3      2019-03-20 [1] CRAN (R 3.5.3)                      
 pkgconfig               2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                      
 pkgload                 1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                      
 plyr                    1.8.4      2016-06-08 [1] CRAN (R 3.5.0)                      
 png                     0.1-7      2013-12-03 [1] CRAN (R 3.5.0)                      
 prettyunits             1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                      
 processx                3.3.0      2019-03-10 [1] CRAN (R 3.5.3)                      
 promises                1.0.1      2018-04-13 [1] CRAN (R 3.5.0)                      
 pryr                    0.1.4      2018-02-18 [1] CRAN (R 3.5.1)                      
 ps                      1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                      
 psych                   1.8.12     2019-01-12 [1] CRAN (R 3.5.2)                      
 purrr                 * 0.3.2      2019-03-15 [1] CRAN (R 3.5.3)                      
 purrrlyr                0.0.5      2019-03-15 [1] CRAN (R 3.5.3)                      
 pwr                     1.2-2      2018-03-03 [1] CRAN (R 3.5.0)                      
 qgraph                  1.6.1      2019-02-13 [1] CRAN (R 3.5.1)                      
 R6                      2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                      
 rapportools             1.0        2014-01-07 [1] CRAN (R 3.5.1)                      
 RColorBrewer            1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                      
 rcompanion              2.1.1      2019-03-02 [1] CRAN (R 3.5.3)                      
 Rcpp                  * 1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                      
 RCurl                   1.95-4.12  2019-03-04 [1] CRAN (R 3.5.2)                      
 readr                 * 1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                      
 readxl                  1.3.1      2019-03-13 [1] CRAN (R 3.5.3)                      
 remotes                 2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                      
 reshape                 0.8.8      2018-10-23 [1] CRAN (R 3.5.1)                      
 reshape2                1.4.3      2017-12-11 [1] CRAN (R 3.5.0)                      
 rgexf                   0.15.3     2015-03-24 [1] CRAN (R 3.5.0)                      
 rio                     0.5.16     2018-11-26 [1] CRAN (R 3.5.1)                      
 rjson                   0.2.20     2018-06-08 [1] CRAN (R 3.5.0)                      
 rlang                   0.3.3      2019-03-29 [1] CRAN (R 3.5.3)                      
 rmarkdown               1.12       2019-03-14 [1] CRAN (R 3.5.3)                      
 robust                  0.4-18     2017-04-27 [1] CRAN (R 3.5.1)                      
 robustbase              0.93-4     2019-03-19 [1] CRAN (R 3.5.3)                      
 Rook                    1.1-1      2014-10-20 [1] CRAN (R 3.5.0)                      
 rpart                   4.1-13     2018-02-23 [1] CRAN (R 3.5.0)                      
 rprojroot               1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                      
 rrcov                   1.4-7      2018-11-15 [1] CRAN (R 3.5.1)                      
 rsconnect               0.8.13     2019-01-10 [1] CRAN (R 3.5.2)                      
 rstan                   2.18.2     2018-11-07 [1] CRAN (R 3.5.1)                      
 rstantools              1.5.1      2018-08-22 [1] CRAN (R 3.5.1)                      
 rstudioapi              0.10       2019-03-19 [1] CRAN (R 3.5.3)                      
 rvest                   0.3.2      2016-06-17 [1] CRAN (R 3.5.0)                      
 sandwich                2.5-0      2018-08-17 [1] CRAN (R 3.5.1)                      
 scales                  1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                      
 SCRT                    1.2.2      2018-03-07 [1] CRAN (R 3.5.0)                      
 sessioninfo             1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                      
 shiny                   1.2.0      2018-11-02 [1] CRAN (R 3.5.1)                      
 shinyjs                 1.0        2018-01-08 [1] CRAN (R 3.5.0)                      
 shinystan               2.5.0      2018-05-01 [1] CRAN (R 3.5.0)                      
 shinythemes             1.1.2      2018-11-06 [1] CRAN (R 3.5.1)                      
 sjlabelled              1.0.17     2019-03-10 [1] CRAN (R 3.5.3)                      
 sjmisc                  2.7.9      2019-03-16 [1] CRAN (R 3.5.3)                      
 sjstats                 0.17.4     2019-03-15 [1] CRAN (R 3.5.3)                      
 skimr                   1.0.5      2019-02-25 [1] CRAN (R 3.5.3)                      
 StanHeaders             2.18.1     2019-01-28 [1] CRAN (R 3.5.2)                      
 stringi                 1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                      
 stringr               * 1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                      
 summarytools          * 0.9.2      2019-02-22 [1] CRAN (R 3.5.1)                      
 SuppDists               1.1-9.4    2016-09-23 [1] CRAN (R 3.5.0)                      
 survival                2.43-3     2018-11-26 [1] CRAN (R 3.5.1)                      
 testthat                2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                      
 TH.data                 1.0-10     2019-01-21 [1] CRAN (R 3.5.2)                      
 threejs                 0.3.1      2017-08-13 [1] CRAN (R 3.5.0)                      
 tibble                * 2.1.1      2019-03-16 [1] CRAN (R 3.5.3)                      
 tidyr                 * 0.8.3      2019-03-01 [1] CRAN (R 3.5.3)                      
 tidyselect              0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                      
 tidyverse             * 1.2.1      2017-11-14 [1] CRAN (R 3.5.1)                      
 TMB                     1.7.15     2018-11-09 [1] CRAN (R 3.5.1)                      
 userfriendlyscience     0.7.2      2018-09-24 [1] CRAN (R 3.5.1)                      
 usethis                 1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                      
 viridis                 0.5.1      2018-03-29 [1] CRAN (R 3.5.1)                      
 viridisLite             0.3.0      2018-02-01 [1] CRAN (R 3.5.0)                      
 visNetwork              2.0.6      2019-03-26 [1] CRAN (R 3.5.1)                      
 whisker                 0.3-2      2013-04-28 [1] CRAN (R 3.5.0)                      
 withr                   2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                      
 WRS2                    0.10-0     2018-06-15 [1] CRAN (R 3.5.0)                      
 xfun                    0.5        2019-02-20 [1] CRAN (R 3.5.1)                      
 XML                     3.98-1.19  2019-03-06 [1] CRAN (R 3.5.2)                      
 xml2                    1.2.0      2018-01-24 [1] CRAN (R 3.5.0)                      
 xtable                  1.8-3      2018-08-29 [1] CRAN (R 3.5.1)                      
 xts                     0.11-2     2018-11-05 [1] CRAN (R 3.5.1)                      
 yaml                    2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                      
 zip                     2.0.1      2019-03-11 [1] CRAN (R 3.5.3)                      
 zoo                     1.8-5      2019-03-21 [1] CRAN (R 3.5.3)                      

[1] C:/rlibs/3.4.2
[2] C:/Program Files/R/R-3.5.3/library

**Comment by dcomtois** [comment]
Do you use `summarytools::` prefix when loading the package? If so, try not doing it... If you still have the same problem, pls try updating the package with 
```
devtools::install_github("dcomtois/summarytools") 
# or
devtools::install_github("dcomtois/summarytools", ref = "dev-currebt")

```
If you're still having the problem let me know. Thx.

**Comment by heinonmatti** [comment]
Hadn't used prefix when loading, but downloaded with 
`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`
and it worked! 

Much love, thanks.

**Comment by Hamedhm** [comment]
Hi,

The bug still exists. I recommend checking for s  before passing to the strsplit in

for (s in list(...)) {
**if(is.null(s)) next**
--
38 | splitted <- unlist(strsplit(s, ""))
39 | intvalues <- utf8ToInt(enc2utf8(s))

**Comment by dcomtois** [comment]
@Hamedhm Thanks for the feedback. What version are you using? The master branch on GH? If so could you pls provide a reproducible example?

Not sure I follow re: bug in dfSummary... Could you pls elaborate, preferably in a new issue?

Cheers!

**Comment by Hamedhm** [comment]
@dcomtois  I use the github version which should be the latest version. 

I cannot provide the example as my data is not released yet. But using strsplit is always tricky as would lead to an error once the first argument is NULL, check this for example, strsplit(NULL,'.')
